version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.9.1
jobs:

  publish:
    <<: *defaults 
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access=public

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
